version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build stravafunction.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - stravafunction
    - samTemplate.yaml
    - outputSamTemplate.yaml