version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build stravafunction.go
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-ap-southeast-2-360285354545 --output-template-file outputSamTemplate.yaml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - stravafunction
    - samTemplate.yaml
    - outputSamTemplate.yaml